import type {
  Category,
  MenuItem,
  Table,
  Floor,
  InventoryItem,
  RestaurantSettings,
} from "./types";
import { generateId } from "./utils";

export const seedCategories: Category[] = [
  {
    id: generateId(),
    name: "Starters",
    description: "Begin your meal with our delicious starters",
    order: 1,
    isActive: true,
    itemCount: 0,
  },
  {
    id: generateId(),
    name: "Main Course",
    description: "Hearty and satisfying main dishes",
    order: 2,
    isActive: true,
    itemCount: 0,
  },
  {
    id: generateId(),
    name: "Pizza",
    description: "Hand-crafted pizzas with fresh ingredients",
    order: 3,
    isActive: true,
    itemCount: 0,
  },
  {
    id: generateId(),
    name: "Burgers",
    description: "Juicy burgers made to order",
    order: 4,
    isActive: true,
    itemCount: 0,
  },
  {
    id: generateId(),
    name: "Salads",
    description: "Fresh and healthy salad options",
    order: 5,
    isActive: true,
    itemCount: 0,
  },
  {
    id: generateId(),
    name: "Beverages",
    description: "Refreshing drinks and beverages",
    order: 6,
    isActive: true,
    itemCount: 0,
  },
  {
    id: generateId(),
    name: "Desserts",
    description: "Sweet endings to your meal",
    order: 7,
    isActive: true,
    itemCount: 0,
  },
];

export function createSeedMenuItems(categories: Category[]): MenuItem[] {
  const catMap = Object.fromEntries(categories.map((c) => [c.name, c.id]));
  const now = new Date().toISOString();

  return [
    {
      id: generateId(),
      categoryId: catMap["Starters"],
      name: "Garlic Bread",
      description: "Crispy bread with garlic butter and herbs",
      price: 5.99,
      image: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=400",
      status: "available",
      isFeatured: false,
      isPopular: true,
      tags: ["vegetarian", "appetizer"],
      addons: [],
      preparationTime: 8,
      calories: 220,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Starters"],
      name: "Chicken Wings",
      description: "Crispy wings tossed in your choice of sauce",
      price: 11.99,
      image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=400",
      status: "available",
      isFeatured: true,
      isPopular: true,
      tags: ["chicken", "spicy"],
      addons: [
        { name: "Extra Sauce", price: 1.0 },
        { name: "Blue Cheese Dip", price: 1.5 },
      ],
      preparationTime: 15,
      calories: 450,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Main Course"],
      name: "Grilled Salmon",
      description: "Atlantic salmon with lemon butter and seasonal vegetables",
      price: 22.99,
      image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400",
      status: "available",
      isFeatured: true,
      isPopular: false,
      tags: ["seafood", "healthy", "gluten-free"],
      addons: [{ name: "Extra Vegetables", price: 2.0 }],
      preparationTime: 20,
      calories: 380,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Main Course"],
      name: "Ribeye Steak",
      description: "12oz prime ribeye with mashed potatoes and gravy",
      price: 34.99,
      image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400",
      status: "available",
      isFeatured: true,
      isPopular: true,
      tags: ["beef", "premium"],
      addons: [
        { name: "Extra Sauce", price: 1.5 },
        { name: "Side Salad", price: 4.0 },
      ],
      preparationTime: 25,
      calories: 780,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Pizza"],
      name: "Margherita Pizza",
      description: "Classic tomato base with fresh mozzarella and basil",
      price: 14.99,
      image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400",
      status: "available",
      isFeatured: false,
      isPopular: true,
      tags: ["vegetarian", "classic"],
      addons: [
        { name: "Extra Cheese", price: 2.0 },
        { name: "Gluten Free Base", price: 3.0 },
      ],
      preparationTime: 18,
      calories: 560,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Pizza"],
      name: "BBQ Chicken Pizza",
      description: "BBQ sauce, grilled chicken, red onion, and cheddar",
      price: 17.99,
      image: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=400",
      status: "available",
      isFeatured: false,
      isPopular: false,
      tags: ["chicken", "bbq"],
      addons: [{ name: "Extra Toppings", price: 1.5 }],
      preparationTime: 20,
      calories: 640,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Burgers"],
      name: "Classic Cheeseburger",
      description: "Beef patty, cheddar, lettuce, tomato, pickles",
      price: 12.99,
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
      status: "available",
      isFeatured: false,
      isPopular: true,
      tags: ["beef", "classic"],
      addons: [
        { name: "Extra Patty", price: 4.0 },
        { name: "Bacon", price: 2.0 },
        { name: "Avocado", price: 2.5 },
      ],
      preparationTime: 12,
      calories: 680,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Burgers"],
      name: "Mushroom Swiss Burger",
      description: "Beef patty, swiss cheese, sauteed mushrooms",
      price: 14.99,
      image: "https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=400",
      status: "available",
      isFeatured: false,
      isPopular: false,
      tags: ["beef", "mushroom"],
      addons: [{ name: "Extra Mushrooms", price: 1.5 }],
      preparationTime: 12,
      calories: 720,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Salads"],
      name: "Caesar Salad",
      description: "Romaine, parmesan, croutons, caesar dressing",
      price: 9.99,
      image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
      status: "available",
      isFeatured: false,
      isPopular: true,
      tags: ["vegetarian", "healthy", "salad"],
      addons: [
        { name: "Grilled Chicken", price: 4.0 },
        { name: "Extra Dressing", price: 0.5 },
      ],
      preparationTime: 8,
      calories: 320,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Beverages"],
      name: "Fresh Lemonade",
      description: "Freshly squeezed lemonade with mint",
      price: 4.99,
      image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400",
      status: "available",
      isFeatured: false,
      isPopular: true,
      tags: ["cold", "refreshing", "vegetarian"],
      addons: [],
      preparationTime: 3,
      calories: 120,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Beverages"],
      name: "Iced Coffee",
      description: "Cold brew coffee with milk and ice",
      price: 5.99,
      image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400",
      status: "available",
      isFeatured: false,
      isPopular: false,
      tags: ["coffee", "cold"],
      addons: [{ name: "Extra Shot", price: 1.0 }],
      preparationTime: 3,
      calories: 150,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Desserts"],
      name: "Chocolate Lava Cake",
      description: "Warm chocolate cake with molten center and vanilla ice cream",
      price: 8.99,
      image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400",
      status: "available",
      isFeatured: true,
      isPopular: true,
      tags: ["chocolate", "dessert", "vegetarian"],
      addons: [{ name: "Extra Ice Cream", price: 2.0 }],
      preparationTime: 12,
      calories: 450,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      categoryId: catMap["Desserts"],
      name: "Cheesecake",
      description: "New York style cheesecake with berry compote",
      price: 7.99,
      image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400",
      status: "available",
      isFeatured: false,
      isPopular: false,
      tags: ["dessert", "vegetarian"],
      addons: [],
      preparationTime: 5,
      calories: 380,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function createSeedFloors(): { floors: Floor[]; tables: Table[] } {
  const floor1Id = generateId();
  const floor2Id = generateId();
  const tables: Table[] = [];

  // Ground Floor tables
  for (let i = 1; i <= 8; i++) {
    tables.push({
      id: generateId(),
      number: `G${i}`,
      floorId: floor1Id,
      capacity: i <= 4 ? 2 : i <= 6 ? 4 : 6,
      status: "available",
      x: ((i - 1) % 4) * 200 + 50,
      y: Math.floor((i - 1) / 4) * 200 + 50,
      shape: i <= 4 ? "round" : "square",
    });
  }

  // First Floor tables
  for (let i = 1; i <= 6; i++) {
    tables.push({
      id: generateId(),
      number: `F${i}`,
      floorId: floor2Id,
      capacity: i <= 2 ? 4 : i <= 4 ? 6 : 8,
      status: "available",
      x: ((i - 1) % 3) * 250 + 50,
      y: Math.floor((i - 1) / 3) * 250 + 50,
      shape: i <= 2 ? "square" : "rectangle",
    });
  }

  const floors: Floor[] = [
    {
      id: floor1Id,
      name: "Ground Floor",
      order: 1,
      tables: tables
        .filter((t) => t.floorId === floor1Id)
        .map((t) => t.id),
    },
    {
      id: floor2Id,
      name: "First Floor",
      order: 2,
      tables: tables
        .filter((t) => t.floorId === floor2Id)
        .map((t) => t.id),
    },
  ];

  return { floors, tables };
}

export const seedInventory: InventoryItem[] = [
  {
    id: generateId(),
    name: "Rice",
    unit: "kg",
    quantity: 50,
    minQuantity: 10,
    cost: 1.5,
    category: "Grains",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Chicken",
    unit: "kg",
    quantity: 25,
    minQuantity: 5,
    cost: 8.0,
    category: "Meat",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Beef",
    unit: "kg",
    quantity: 20,
    minQuantity: 5,
    cost: 12.0,
    category: "Meat",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Olive Oil",
    unit: "litre",
    quantity: 8,
    minQuantity: 2,
    cost: 6.0,
    category: "Oil",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Tomatoes",
    unit: "kg",
    quantity: 15,
    minQuantity: 5,
    cost: 2.0,
    category: "Vegetables",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Flour",
    unit: "kg",
    quantity: 30,
    minQuantity: 10,
    cost: 0.8,
    category: "Grains",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Mozzarella",
    unit: "kg",
    quantity: 10,
    minQuantity: 3,
    cost: 9.0,
    category: "Dairy",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Salmon",
    unit: "kg",
    quantity: 8,
    minQuantity: 2,
    cost: 18.0,
    category: "Seafood",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Coffee Beans",
    unit: "kg",
    quantity: 3,
    minQuantity: 1,
    cost: 15.0,
    category: "Beverages",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: "Lemons",
    unit: "kg",
    quantity: 5,
    minQuantity: 2,
    cost: 1.5,
    category: "Fruits",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const defaultSettings: RestaurantSettings = {
  name: "Zunayed Restaurant",
  tagline: "Fine Dining & Fresh Flavors",
  address: "123 Main Street, Dhaka, Bangladesh",
  phone: "+880 1234-567890",
  email: "hello@zunayedrestaurant.com",
  currency: "USD",
  taxRate: 8.5,
  openingHours: [
    { day: "Monday", open: "09:00", close: "22:00", isOpen: true },
    { day: "Tuesday", open: "09:00", close: "22:00", isOpen: true },
    { day: "Wednesday", open: "09:00", close: "22:00", isOpen: true },
    { day: "Thursday", open: "09:00", close: "22:00", isOpen: true },
    { day: "Friday", open: "09:00", close: "23:00", isOpen: true },
    { day: "Saturday", open: "10:00", close: "23:00", isOpen: true },
    { day: "Sunday", open: "10:00", close: "21:00", isOpen: true },
  ],
  theme: "light",
  posSettings: {
    defaultDiscount: 0,
    requireTableForDineIn: true,
    printReceiptByDefault: false,
  },
  notificationSettings: {
    emailNotifications: true,
    soundAlerts: true,
    lowStockThreshold: 5,
  },
};
